# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='server',
  syntax='proto3',
  serialized_options=b'\n\013newton.grpcB\006ServerP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cserver.proto\x12\x06server\"!\n\x11\x43onnectionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x0f\x43onnectionReply\x12\x0e\n\x06result\x18\x01 \x01(\t2M\n\nConnection\x12?\n\x07\x43onnect\x12\x19.server.ConnectionRequest\x1a\x17.server.ConnectionReply\"\x00\x42\x1d\n\x0bnewton.grpcB\x06ServerP\x01\xa2\x02\x03HLWb\x06proto3'
)




_CONNECTIONREQUEST = _descriptor.Descriptor(
  name='ConnectionRequest',
  full_name='server.ConnectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='server.ConnectionRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=57,
)


_CONNECTIONREPLY = _descriptor.Descriptor(
  name='ConnectionReply',
  full_name='server.ConnectionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='server.ConnectionReply.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['ConnectionRequest'] = _CONNECTIONREQUEST
DESCRIPTOR.message_types_by_name['ConnectionReply'] = _CONNECTIONREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectionRequest = _reflection.GeneratedProtocolMessageType('ConnectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:server.ConnectionRequest)
  })
_sym_db.RegisterMessage(ConnectionRequest)

ConnectionReply = _reflection.GeneratedProtocolMessageType('ConnectionReply', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONREPLY,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:server.ConnectionReply)
  })
_sym_db.RegisterMessage(ConnectionReply)


DESCRIPTOR._options = None

_CONNECTION = _descriptor.ServiceDescriptor(
  name='Connection',
  full_name='server.Connection',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=94,
  serialized_end=171,
  methods=[
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='server.Connection.Connect',
    index=0,
    containing_service=None,
    input_type=_CONNECTIONREQUEST,
    output_type=_CONNECTIONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONNECTION)

DESCRIPTOR.services_by_name['Connection'] = _CONNECTION

# @@protoc_insertion_point(module_scope)
